### ISSUE TITLE
neat doesnt have a config attribute, please provide a turnaround

### ISSUE THREAD

**Issue by jaichaudhry323** [NeuralNine/ai-car-simulation#2]
After doing pip install neat, this showed up:
-----------------------------------------------------------------
AttributeError                  Traceback (most recent call last)
<ipython-input-4-d7603e8aac53> in <module>
      3     # Load Config
      4     config_path = "./config.txt"
----> 5     config = neat.config.Config(neat.DefaultGenome,
      6                                 neat.DefaultReproduction,
      7                                 neat.DefaultSpeciesSet,

AttributeError: module 'neat' has no attribute 'config'

![image](https://user-images.githubusercontent.com/42890838/109016781-828b9300-76dc-11eb-8d6a-32def7e2dda6.png)

**Comment by warmpigman** [comment]
pip install neat-python

**Comment by Surfer2010** [comment]
Hello, i don't get it to run on windows

```
C:\Users\abc>python C:\Users\abc\Downloads\ai-car\newcar.py
pygame 2.0.1 (SDL 2.0.14, Python 3.9.5)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "C:\Users\abc\Downloads\ai-car\newcar.py", line 248, in <module>
    config = neat.config.Config(neat.DefaultGenome,
AttributeError: module 'neat' has no attribute 'config'

```
tryied this

```
C:\Users\abc>python -m pip install neat-python
Collecting neat-python
  Downloading neat_python-0.92-py3-none-any.whl (44 kB)
     |████████████████████████████████| 44 kB 809 kB/s
Installing collected packages: neat-python
Successfully installed neat-python-0.92
WARNING: You are using pip version 21.1.1; however, version 21.1.2 is available.
You should consider upgrading via the 'C:\Users\abc\AppData\Local\Programs\Python\Python39\python.exe -m pip install --upgrade pip' command.
```
new try

```
C:\Users\abc>python C:\Users\abc\Downloads\ai-car\newcar.py
pygame 2.0.1 (SDL 2.0.14, Python 3.9.5)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "C:\Users\abc\Downloads\ai-car\newcar.py", line 248, in <module>
    config = neat.config.Config(neat.DefaultGenome,
  File "C:\Users\abc\AppData\Local\Programs\Python\Python39\lib\site-packages\neat\config.py", line 153, in __init__
    raise Exception('No such config file: ' + os.path.abspath(filename))
Exception: No such config file: C:\Users\abc\config.txt
```
