### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by Surfer2010** [NeuralNine/ai-car-simulation#5]
Hello, I got this error:

```
 ****** Running generation 0 ******

Traceback (most recent call last):
  File "C:\Users\Dom\Downloads\ai-car\newcar.py", line 261, in <module>
    population.run(run_simulation, 1000)
  File "C:\Users\Dom\AppData\Local\Programs\Python\Python39\lib\site-packages\neat\population.py", line 89, in run
    fitness_function(list(iteritems(self.population)), self.config)
  File "C:\Users\Dom\Downloads\ai-car\newcar.py", line 173, in run_simulation
    cars.append(Car())
  File "C:\Users\Dom\Downloads\ai-car\newcar.py", line 30, in __init__
    self.sprite = pygame.image.load('car.png').convert() # Convert Speeds Up A Lot
FileNotFoundError: No such file or directory.
```

**Comment by Rachit333** [comment]
Download all the files and make sure they are all in same folder. Then try again!!
